{% set name = "databind.core" %}
{% set version = "1.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/databind.core-{{ version }}.tar.gz
  sha256: ae6e13da4e30ebff447e003f92c0f2fe38b70f03502ef9e2afed24991d6b54bc

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - deprecated >=1.2.12,<2.0.0
    - nr.optional >=0.1.1,<1.0.0
    - nr.parsing.date >=1.0.1,<2.0.0
    - nr.preconditions >=0.0.4,<1.0.0
    - nr.stream >=0.1.1,<1.0.0
    - python >={{ python_min }},<4.0
    - typing-extensions <4.0.0,>=3.10.0

test:
  imports:
    - databind
    - databind.core
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/NiklasRosenstein/python-databind
  summary: Databind is a library inspired by jackson-databind to de-/serialize Python dataclasses. Compatible with Python 3.7 and newer.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - NiklasRosenstein
