{% set name = "databind.core" %}
{% set version = "1.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/databind.core-{{ version }}.tar.gz
  sha256: f22514f76d9907be8c3b92289c07fb7ab92cbc5598140e4e2bef4c29474201ef

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<4.0
  run:
    - deprecated >=1.2.12,<2.0.0
    - nr.util >=0.8.3,<1.0.0
    - python >=3.7,<4.0
    - typing-extensions <4.0.0,>=3.10.0

test:
  imports:
    - databind
    - databind.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NiklasRosenstein/python-databind
  summary: Databind is a library inspired by jackson-databind to de-/serialize Python dataclasses. Compatible with Python 3.7 and newer.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - NiklasRosenstein
